#!/sbin/sh

. "$env"

touch "$tmp/save"
touch "$tmp/abort"

print
print "You can now modify your recovery image contents via ADB."
print "Your ramdisk contents are located at:"
print "$ramdisk"
print
print "To finish your work and flash the modified recovery image, simply execute:"
print "echo 1 > $tmp/save"
print
print "If you would like to abort your modifications, you can instead execute:"
print "echo 1 > $tmp/abort"
print

while true; do
	[ -s "$tmp/abort" ] && abort "Ignoring modifications and aborting..."
	[ -s "$tmp/save" ] && break
	sleep 1
done

print "Done modifications, continuing with flash!"

exit 0
