#!/sbin/sh

. "$env"

print "Setting adb to insecure..."

# make sure adb is not secure
replace_line default.prop "ro.adb.secure=1" "ro.adb.secure=0"
replace_line default.prop "ro.secure=1" "ro.secure=0"
