#!/sbin/sh

. "$env"

[ -f sepolicy ] && {
	print "Patching the sepolicy for SuperSU..."
	LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$bin" $bin/supolicy --file sepolicy sepolicy_1
}
[ -f sepolicy_1 ] && {
	rm sepolicy
	mv sepolicy_1 sepolicy
	chmod 0644 sepolicy
	print "Success!"
} || {
	abort "Unable to patch the sepolicy!"
}
