#!/sbin/sh

. "$env"

#print "Removing Samsung secure kernel info..."
#rm /system/*info*

print "Disabling unauthorized changes warnings..."
rm -rf /system/app/SecurityLogAgent*

#print "Removing Knox container initialization"
#rm "$ramdisk/init.container.rc"

#print "Removing Knox apps, framework, and libraries..."
#rm -rf /system/app/Knox*
#rm -rf /system/container
#rm -rf /system/etc/secure_storage
#rm -rf /system/framework/*knox*
#rm -rf /system/lib/*knox*
#rm -rf /system/preloadedmdm/*KNOX*

print "Disabling Knox configuration..."
setprop ro.config.knox 0
setprop ro.config.kap false
delprop ro.config.kap_default_on
setprop ro.securestorage.support false

#print "Removing TIMA framework and libraries..."
#rm -f /system/bin/*tima*
#rm -f /system/framework/*tima*
#rm -f /system/lib/*tima*

print "Disabling TIMA configuration..."
#setprop ro.config.tima 0
setprop ro.config.rkp false
#delprop ro.config.timaversion

print "Disabling HDCP enforcing..."
setprop wlan.wfd.hdcp disable

exit 0
